name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - 'docs/**'

jobs:  
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker BuildKit
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build in dev container
      uses: stuartleeks/devcontainer-build-run@v0.1
      id: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_NUMBER: ${{ github.run_id }}
        IS_PR: ${{ github.head_ref }}
        BRANCH: ${{ github.ref }}
      with:
        imageName: ghcr.io/stuartleeks/site-cert-checker-devcontainer
        runCmd: |
          echo "Starting"
          ./scripts/ci.sh
        env: |
          BUILD_NUMBER
          IS_CI=1
          IS_PR
          BRANCH

    - uses: actions/upload-artifact@v2
      name: Create Function zip Artifact
      with:
        name: functions
        path: ./build-output/functions.zip
        if-no-files-found: error 
